### ISSUE TITLE
AgoraCloud Business Related Work

### ISSUE THREAD

**Issue by saidghamra** [AgoraCloud/frontend#94]
In this issue, @MarcDAFrame will continuously give small updates regarding his progress on the AgoraCloud landing page, pitch deck and pricing models for hosted AgoraCloud (SaaS).

**Comment by MarcDAFrame** [comment]
https://edu.mframe.ca

**Comment by saidghamra** [comment]
![image](https://user-images.githubusercontent.com/35788699/143964666-a5de0b7a-2ebb-443d-a4ec-f1b4a2431af7.png)

![image](https://user-images.githubusercontent.com/35788699/143964679-fc544533-80a4-4c07-a662-651214d1cc41.png)

![image](https://user-images.githubusercontent.com/35788699/143964690-4d44525f-cc9c-45ab-ba6b-900244731bdb.png)

**Comment by MarcDAFrame** [comment]
![screencapture-edu-mframe-ca-2021-11-29-19_39_14](https://user-images.githubusercontent.com/12240832/143964723-6c77d63d-f683-4c10-a90d-e0ab0e1ce524.png)

**Comment by MarcDAFrame** [comment]
# TODO
- [ ] compare costs between clouds, server space, on prem hosting

**Comment by MarcDAFrame** [comment]
![image](https://user-images.githubusercontent.com/12240832/144534533-1b8700c5-7da3-4593-9e70-32417a6fa856.png)

**Comment by saidghamra** [comment]
Closing this since today (December 8, 2021) is the last day of classes. We will resume working on this issue at a later date after our finals are done and we have discussed our strategy moving forward.
